version: '3.8'

services:
  web:
    build: .
    container_name: todoapp_web
    ports:
      - "8000:8000"

    environment:
      - TZ=Asia/Baku
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
